import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import SearchBar from "./components/SearchBar";
import ClientProvider from "./components/ClientProvider"; // Import ClientProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientProvider>
          <div className="bg-white dark:bg-[#333333] dark:text-white transition-colors duration-300 min-h-screen">
            <Header />
            <div>
              <SearchBar />
            </div>
            {children}
          </div>
        </ClientProvider>
      </body>
    </html>
  );
}
